---
name: Minimal CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate Move Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.86.0"

      - name: Install Sui CLI
        run: |
          cargo install --locked --git https://github.com/MystenLabs/sui.git \
            --tag "testnet-v1.48.1" sui
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Verify Tools
        run: |
          rustc --version
          cargo --version
          sui --version

      - name: Build Move Project
        run: |
          sui move build --path .

      - name: Test Move Project
        run: |
          sui move test --path .