---
name: Dependency Management & Updates

on:
  schedule:
    # Check for dependency updates daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update to perform'
        required: true
        default: 'check'
        type: choice
        options:
          - check
          - update

jobs:
  # Check Rust dependencies for updates
  check-rust-dependencies:
    name: Check Rust Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.86.0"

      - name: Install Cargo Tools
        run: |
          cargo install cargo-outdated cargo-audit

      - name: Check for Outdated Dependencies
        run: |
          echo "Checking for outdated dependencies..."
          cargo outdated --workspace || echo "No outdated dependencies found"

      - name: Run Security Audit
        run: |
          echo "Running security audit..."
          cargo audit || echo "Security audit completed"

  # Check Sui version updates
  check-sui-version:
    name: Check Sui Version Updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Current Sui Version
        run: |
          echo "Current Sui version in workflows:"
          grep -r "testnet-v" .github/workflows/ || echo "No Sui version found"

      - name: Check Latest Sui Release
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const { data: releases } = await github.rest.repos.listReleases({
                owner: 'MystenLabs',
                repo: 'sui',
                per_page: 5
              });

              console.log('Latest Sui releases:');
              releases.forEach(release => {
                console.log(`- ${release.tag_name}: ${release.name}`);
              });
            } catch (error) {
              console.log('Could not fetch Sui releases:', error.message);
            }

  # Check GitHub Actions versions
  check-action-versions:
    name: Check GitHub Actions Versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Action Versions
        run: |
          echo "Checking GitHub Actions versions used:"
          grep -r "uses:" .github/workflows/ | grep -v ".disabled" | sort | uniq

      - name: Check for Action Updates
        run: |
          echo "Common actions to check for updates:"
          echo "- actions/checkout (current: v4)"
          echo "- actions/setup-node (current: v3)" 
          echo "- actions/upload-artifact (current: v3)"
          echo "- dtolnay/rust-toolchain (current: stable)"

  # Generate dependency report
  dependency-report:
    name: Generate Dependency Report
    runs-on: ubuntu-latest
    needs: [check-rust-dependencies, check-sui-version, check-action-versions]
    if: always()

    steps:
      - name: Generate Summary Report
        run: |
          echo "# Dependency Management Report - $(date)" > dependency-report.md
          echo "" >> dependency-report.md
          echo "## Summary" >> dependency-report.md
          echo "- Rust dependencies checked ✅" >> dependency-report.md
          echo "- Sui version checked ✅" >> dependency-report.md
          echo "- GitHub Actions versions checked ✅" >> dependency-report.md
          echo "" >> dependency-report.md
          echo "## Recommendations" >> dependency-report.md
          echo "- Review dependency updates regularly" >> dependency-report.md
          echo "- Keep Sui CLI version updated with latest testnet releases" >> dependency-report.md
          echo "- Update GitHub Actions to latest versions when available" >> dependency-report.md

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-report-${{ github.sha }}
          path: dependency-report.md
          retention-days: 30