---
name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Security Tools
        run: |
          cargo install cargo-audit

      - name: Run Security Audit
        continue-on-error: true
        run: |
          cargo audit

      - name: Analyze Move Files
        run: |
          echo "Analyzing Move files for security patterns..."
          find . -name "*.move" -exec echo "Checking: {}" \;
          echo "Security scan completed"